apiVersion: v1
kind: Service
metadata:
  name: barinak-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: barinak
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
